#!/usr/bin/env bash

botToken="BOT TOKEN";  # id bot telegram
channelId="ID CANNEL TELEGRAM"; # id cannel telegram
postImage=`sort --random-sort /home/tpp/imgcat/catimg.list | head -n 1`  # path

curl -v -F "chat_id=$channelId" -F photo=@$postImage https://api.telegram.org/bot$botToken/sendPhoto   # source code and API telegram

removeImage=`echo $postImage | cut -d "/" -f 6`; #remove from the list
sed -i "/$removeImage/d" /home/tpp/imgcat/catimg.list;

exit 0; 
